package com.tockycode.app;

import android.os.Bundle;
import android.view.View;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import java.util.HashMap;
import java.util.Map;

/**
 * TockyCode - Professional AI Code Generator
 * Android Application
 * 100% Free, Local AI-powered code generation
 */
public class MainActivity extends AppCompatActivity {

    private EditText promptInput;
    private TextView outputCode;
    private Spinner languageSpinner;
    private Button generateButton;
    private Button clearButton;
    private Button copyButton;

    // Local code generation templates (works offline)
    private final Map<String, CodeTemplate> templates = new HashMap<>();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Initialize UI components
        promptInput = findViewById(R.id.promptInput);
        outputCode = findViewById(R.id.outputCode);
        languageSpinner = findViewById(R.id.languageSpinner);
        generateButton = findViewById(R.id.generateButton);
        clearButton = findViewById(R.id.clearButton);
        copyButton = findViewById(R.id.copyButton);

        // Setup language spinner
        String[] languages = {"Python", "JavaScript", "Java", "C++", "Go", "Rust", "TypeScript"};
        ArrayAdapter<String> adapter = new ArrayAdapter<>(this, 
                android.R.layout.simple_spinner_item, languages);
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
        languageSpinner.setAdapter(adapter);

        // Initialize templates
        initTemplates();

        // Button click listeners
        generateButton.setOnClickListener(v -> generateCode());
        clearButton.setOnClickListener(v -> clearOutput());
        copyButton.setOnClickListener(v -> copyToClipboard());
    }

    private void initTemplates() {
        templates.put("Python", new CodeTemplate("python", 
            "def {{function_name}}():\n    \"\"\"Generated by TockyCode\"\"\"\n    pass\n\n# Main\{{function_name}}()"
        ));

        templates.put("JavaScript", new CodeTemplate("javascript",
            "/** TockyCode Generated */\nconst {{function_name}} = () => {\n    // Add your code here\n};\n\nexport default {{function_name}};"
        ));

        templates.put("Java", new CodeTemplate("java",
            "package com.tockycode.app;\n\n/** TockyCode Generated */\npublic class {{class_name}} {\n    public static void main(String[] args) {\n        // Add your code here\n    }\n}"
        ));

        templates.put("C++", new CodeTemplate("cpp",
            "#include <iostream>\n\n// TockyCode Generated\nint main() {\n    // Add your code here\n    return 0;\n}"
        ));

        templates.put("Go", new CodeTemplate("go",
            "package main\n\nimport \"fmt\"\n\n// TockyCode Generated\nfunc main() {\n    fmt.Println(\"Hello from TockyCode\")\n}"
        ));

        templates.put("Rust", new CodeTemplate("rust",
            "// TockyCode Generated\nfn main() {\n    println!(\"Hello from TockyCode\");\n}"
        ));

        templates.put("TypeScript", new CodeTemplate("typescript",
            "// TockyCode Generated\nfunction {{function_name}}(): void {\n    // Add your code here\n}\n\nexport { {{function_name}} };"
        ));
    }

    private void generateCode() {
        String prompt = promptInput.getText().toString().trim();
        String language = languageSpinner.getSelectedItem().toString();

        if (prompt.isEmpty()) {
            Toast.makeText(this, "Please enter a prompt", Toast.LENGTH_SHORT).show();
            return;
        }

        // Generate code based on prompt and language
        String generatedCode = generateFromPrompt(prompt, language);
        outputCode.setText(generatedCode);
        outputCode.setVisibility(View.VISIBLE);
    }

    private String generateFromPrompt(String prompt, String language) {
        String lowerPrompt = prompt.toLowerCase();

        // Check for specific patterns in prompt
        if (lowerPrompt.contains("api") || lowerPrompt.contains("rest") || lowerPrompt.contains("server")) {
            return generateAPICode(language);
        } else if (lowerPrompt.contains("class")) {
            return generateClassCode(language);
        } else if (lowerPrompt.contains("function") || lowerPrompt.contains("method")) {
            return generateFunctionCode(language);
        } else if (lowerPrompt.contains("database") || lowerPrompt.contains("sql")) {
            return generateDatabaseCode(language);
        } else if (lowerPrompt.contains("cli") || lowerPrompt.contains("command")) {
            return generateCLICode(language);
        }

        // Default template
        CodeTemplate template = templates.get(language);
        if (template != null) {
            return template.code
                    .replace("{{function_name}}", "generated_function")
                    .replace("{{class_name}}", "GeneratedClass");
        }
        return "// TockyCode: Code generation not available for this language";
    }

    private String generateAPICode(String language) {
        switch (language) {
            case "Python":
                return "from flask import Flask, jsonify\n\napp = Flask(__name__)\n\n@app.route('/api/health')\ndef health():\n    return jsonify({'status': 'ok', 'version': '1.0.0'})\n\n@app.route('/api/data', methods=['GET'])\ndef get_data():\n    return jsonify({'data': []})\n\nif __name__ == '__main__':\n    app.run(debug=True, port=5000)";
            case "JavaScript":
                return "const express = require('express');\nconst app = express();\n\napp.get('/api/health', (req, res) => {\n    res.json({ status: 'ok', version: '1.0.0' });\n});\n\napp.get('/api/data', (req, res) => {\n    res.json({ data: [] });\n});\n\napp.listen(3000, () => console.log('Server running on port 3000'));";
            case "Java":
                return "import org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\nimport org.springframework.web.bind.annotation.*;\n\n@SpringBootApplication\n@RestController\npublic class ApiApplication {\n    @GetMapping(\"/api/health\")\n    public Map<String, String> health() {\n        return Map.of(\"status\", \"ok\", \"version\", \"1.0.0\");\n    }\n    \n    public static void main(String[] args) {\n        SpringApplication.run(ApiApplication.class, args);\n    }\n}";
            default:
                return "// API code generation for " + language;
        }
    }

    private String generateClassCode(String language) {
        switch (language) {
            case "Python":
                return "class DataProcessor:\n    \"\"\"Professional data processor\"\"\"\n    \n    def __init__(self):\n        self.data = []\n        \n    def add(self, item):\n        self.data.append(item)\n        return self\n    \n    def process(self):\n        return [item for item in self.data]\n    \n    def clear(self):\n        self.data.clear()\n\nif __name__ == '__main__':\n    processor = DataProcessor()\n    print(processor.add('test').process())";
            case "JavaScript":
                return "class AppManager {\n    constructor() {\n        this.data = [];\n    }\n    \n    add(item) {\n        this.data.push(item);\n        return this;\n    }\n    \n    process() {\n        return this.data.map(item => item);\n    }\n    \n    clear() {\n        this.data = [];\n    }\n}\n\nexport default AppManager;";
            case "Java":
                return "public class DataProcessor {\n    private List<Object> data = new ArrayList<>();\n    \n    public void add(Object item) {\n        data.add(item);\n    }\n    \n    public List<Object> process() {\n        return new ArrayList<>(data);\n    }\n    \n    public void clear() {\n        data.clear();\n    }\n}";
            default:
                return "// Class code for " + language;
        }
    }

    private String generateFunctionCode(String language) {
        switch (language) {
            case "Python":
                return "def calculate_result(value: float) -> float:\n    \"\"\"Calculate result based on input.\"\"\"\n    import math\n    return math.sqrt(abs(value)) * 2\n\n# Usage\nif __name__ == '__main__':\n    result = calculate_result(25)\n    print(f'Result: {result}')";
            case "JavaScript":
                return "function calculateResult(value) {\n    return Math.sqrt(Math.abs(value)) * 2;\n}\n\n// Usage\nconsole.log('Result:', calculateResult(25));";
            case "Java":
                return "public static double calculateResult(double value) {\n    return Math.sqrt(Math.abs(value)) * 2;\n}\n\n// Usage\npublic static void main(String[] args) {\n    System.out.println(\"Result: \" + calculateResult(25));\n}";
            default:
                return "// Function code for " + language;
        }
    }

    private String generateDatabaseCode(String language) {
        switch (language) {
            case "Python":
                return "import sqlite3\nfrom typing import List, Dict, Optional\n\nclass DatabaseManager:\n    def __init__(self, db_path: str = 'app.db'):\n        self.db_path = db_path\n        self._init_db()\n    \n    def _init_db(self):\n        conn = sqlite3.connect(self.db_path)\n        conn.execute('''\n            CREATE TABLE IF NOT EXISTS users (\n                id INTEGER PRIMARY KEY,\n                username TEXT UNIQUE,\n                email TEXT UNIQUE\n            )\n        ''')\n        conn.commit()\n        conn.close()\n    \n    def create_user(self, username: str, email: str) -> int:\n        conn = sqlite3.connect(self.db_path)\n        cursor = conn.cursor()\n        cursor.execute('INSERT INTO users (username, email) VALUES (?, ?)', \n                     (username, email))\n        conn.commit()\n        user_id = cursor.lastrowid\n        conn.close()\n        return user_id\n\n# Usage\ndb = DatabaseManager('example.db')\nuser_id = db.create_user('john', 'john@example.com')\nprint(f'Created user: {user_id}')";
            default:
                return "// Database code for " + language;
        }
    }

    private String generateCLICode(String language) {
        switch (language) {
            case "Python":
                return "#!/usr/bin/env python3\nimport argparse\nimport sys\n\ndef main():\n    parser = argparse.ArgumentParser(description='TockyCode CLI')\n    parser.add_argument('-p', '--prompt', help='Code prompt')\n    parser.add_argument('-l', '--language', default='python', help='Language')\n    parser.add_argument('-o', '--output', help='Output file')\n    args = parser.parse_args()\n    \n    if args.prompt:\n        print(f'Generating {args.language} code for: {args.prompt}')\n\nif __name__ == '__main__':\n    main()";
            default:
                return "// CLI code for " + language;
        }
    }

    private void clearOutput() {
        promptInput.setText("");
        outputCode.setText("");
        outputCode.setVisibility(View.GONE);
    }

    private void copyToClipboard() {
        String code = outputCode.getText().toString();
        if (code.isEmpty()) {
            Toast.makeText(this, "No code to copy", Toast.LENGTH_SHORT).show();
            return;
        }

        android.content.ClipboardManager clipboard = 
            (android.content.ClipboardManager) getSystemService(CLIPBOARD_SERVICE);
        android.content.ClipData clip = android.content.ClipData.newPlainText("TockyCode", code);
        clipboard.setPrimaryClip(clip);
        Toast.makeText(this, "Code copied to clipboard", Toast.LENGTH_SHORT).show();
    }

    // Inner class for code templates
    private static class CodeTemplate {
        String language;
        String code;

        CodeTemplate(String language, String code) {
            this.language = language;
            this.code = code;
        }
    }
}