import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  runApp(const TockyCodeApp());
}

class TockyCodeApp extends StatelessWidget {
  const TockyCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'TockyCode',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        colorScheme: ColorScheme.dark(
          primary: const Color(0xFF00D9FF),
          secondary: const Color(0xFF00FF88),
          surface: const Color(0xFF1E1E1E),
          onSurface: Colors.white,
        ),
        scaffoldBackgroundColor: const Color(0xFF1E1E1E),
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF1E1E1E),
          elevation: 0,
          centerTitle: true,
        ),
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFF2D2D2D),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide.none,
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFF00D9FF), width: 2),
          ),
        ),
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: const Color(0xFF00D9FF),
            foregroundColor: Colors.black,
            padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
          ),
        ),
      ),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final TextEditingController _promptController = TextEditingController();
  String _selectedLanguage = 'Python';
  String _generatedCode = '';
  bool _isLoading = false;
  bool _showCode = false;

  final List<String> _languages = [
    'Python',
    'JavaScript',
    'Java',
    'C++',
    'Go',
    'Rust',
    'TypeScript',
    'C',
    'C#',
    'Ruby',
    'PHP',
    'Swift',
    'Kotlin',
  ];

  // Local code generation templates (works offline - 100% free)
  final Map<String, Map<String, String>> _templates = {
    'Python': {
      'function': '''def {{name}}({{params}}):
    """Generated by TockyCode"""
    # Add your implementation here
    return result

# Usage
result = {{name}}({{args}})
print(f"Result: {result}")''',
      'class': '''class {{name}}:
    """Professional {{name}} class"""
    
    def __init__(self{{init_params}}):
        self.data = []
    
    def add(self, item):
        self.data.append(item)
        return self
    
    def process(self):
        return [item for item in self.data]

# Usage
obj = {{name}}({{init_args}})
obj.add("test").add("demo")
print(obj.process())''',
      'api': '''from flask import Flask, jsonify, request
from typing import List, Dict, Any

app = Flask(__name__)
data_store: List[Dict[str, Any]] = []

@app.route("/api/health")
def health():
    return jsonify({"status": "healthy", "version": "1.0.0"})

@app.route("/api/data", methods=["GET"])
def get_all():
    return jsonify({"data": data_store})

@app.route("/api/data", methods=["POST"])
def create():
    data = request.get_json()
    data["id"] = len(data_store) + 1
    data_store.append(data)
    return jsonify({"success": True, "data": data})

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)''',
      'cli': '''#!/usr/bin/env python3
import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description="TockyCode CLI")
    parser.add_argument("-p", "--prompt", help="Code prompt")
    parser.add_argument("-l", "--language", default="python", help="Language")
    parser.add_argument("-o", "--output", help="Output file")
    args = parser.parse_args()
    
    if args.prompt:
        print(f"Generating {args.language} code for: {args.prompt}")

if __name__ == "__main__":
    main()''',
      'database': '''import sqlite3
from typing import List, Dict, Optional

class DatabaseManager:
    def __init__(self, db_path: str = "app.db"):
        self.db_path = db_path
        self._init_db()
    
    def _init_db(self):
        conn = sqlite3.connect(self.db_path)
        conn.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY,
                username TEXT UNIQUE,
                email TEXT UNIQUE
            )
        """)
        conn.commit()
        conn.close()
    
    def create_user(self, username: str, email: str) -> int:
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute("INSERT INTO users (username, email) VALUES (?, ?)", 
                      (username, email))
        conn.commit()
        user_id = cursor.lastrowid
        conn.close()
        return user_id

# Usage
db = DatabaseManager("example.db")
user_id = db.create_user("john", "john@example.com")
print(f"Created user: {user_id}")''',
    },
    'JavaScript': {
      'function': '''// TockyCode Generated
function {{name}}({{params}}) {
    // Add your implementation here
    return result;
}

// Usage
const result = {{name}}({{args}});
console.log("Result:", result);''',
      'class': '''// TockyCode Generated
class {{name}} {
    constructor({{init_params}}) {
        this.data = [];
    }
    
    add(item) {
        this.data.push(item);
        return this;
    }
    
    process() {
        return this.data.map(item => item);
    }
}

// Usage
const obj = new {{name}}({{init_args}});
obj.add("test").add("demo");
console.log(obj.process());''',
      'api': '''const express = require('express');
const app = express();
app.use(express.json());

const dataStore = [];

app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', version: '1.0.0' });
});

app.get('/api/data', (req, res) => {
    res.json({ data: dataStore });
});

app.post('/api/data', (req, res) => {
    const item = { id: dataStore.length + 1, ...req.body };
    dataStore.push(item);
    res.json({ success: true, data: item });
});

app.listen(3000, () => console.log('Server on port 3000'));''',
      'cli': '''#!/usr/bin/env node
const { program } = require('commander');

program
  .name('tockycode')
  .description('TockyCode CLI')
  .version('1.0.0');

program
  .command('generate')
  .option('-p, --prompt <prompt>', 'Code prompt')
  .option('-l, --language <language>', 'Language', 'javascript')
  .action((options) => {
    console.log("Generating <language> code for: <prompt>");
  });

program.parse();''',
      'database': '''// TockyCode Generated - SQLite with better-sqlite3
const Database = require('better-sqlite3');
const db = new Database('app.db');

db.exec(`
  CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username TEXT UNIQUE,
    email TEXT UNIQUE
  )
`);

function createUser(username, email) {
    const stmt = db.prepare('INSERT INTO users (username, email) VALUES (?, ?)');
    const result = stmt.run(username, email);
    return result.lastInsertRowid;
}

const userId = createUser('john', 'john@example.com');
console.log('Created user:', userId);''',
    },
    'Java': {
      'function': '''// TockyCode Generated
public class {{name}} {
    public static {{returnType}} {{name}}({{params}}) {
        // Add your implementation here
        return result;
    }
    
    public static void main(String[] args) {
        {{returnType}} result = {{name}}({{args}});
        System.out.println("Result: " + result);
    }
}''',
      'class': '''// TockyCode Generated
public class {{name}} {
    private List<Object> data = new ArrayList<>();
    
    public {{name}}({{init_params}}) {
        // Constructor
    }
    
    public void add(Object item) {
        data.add(item);
    }
    
    public List<Object> process() {
        return new ArrayList<>(data);
    }
    
    public static void main(String[] args) {
        {{name}} obj = new {{name}}({{init_args}});
        obj.add("test");
        System.out.println(obj.process());
    }
}''',
      'api': '''// TockyCode Generated - Spring Boot
package com.tockycode.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.*;
import java.util.*;

@SpringBootApplication
@RestController
public class ApiApplication {
    private List<Map<String, Object>> dataStore = new ArrayList<>();
    
    @GetMapping("/api/health")
    public Map<String, String> health() {
        return Map.of("status", "ok", "version", "1.0.0");
    }
    
    @GetMapping("/api/data")
    public Map<String, Object> getAll() {
        return Map.of("data", dataStore);
    }
    
    @PostMapping("/api/data")
    public Map<String, Object> create(@RequestBody Map<String, Object> data) {
        data.put("id", dataStore.size() + 1);
        dataStore.add(data);
        return Map.of("success", true, "data", data);
    }
    
    public static void main(String[] args) {
        SpringApplication.run(ApiApplication.class, args);
    }
}''',
      'cli': '''// TockyCode Generated - Picocli
import picocli.CommandLine;
import picocli.CommandLine.Command;

@Command(name = "tockycode", description = "TockyCode CLI")
public class Main implements Runnable {
    
    @CommandOption(names = {"-p", "--prompt"}, description = "Code prompt")
    private String prompt;
    
    @CommandOption(names = {"-l", "--language"}, description = "Language", defaultValue = "java")
    private String language;
    
    public static void main(String[] args) {
        System.exit(CommandLine.call(Main.class, args));
    }
    
    public void run() {
        System.out.println("Generating " + language + " code for: " + prompt);
    }
}''',
      'database': '''// TockyCode Generated - JDBC
import java.sql.*;

public class DatabaseManager {
    private Connection conn;
    
    public DatabaseManager(String dbPath) throws SQLException {
        conn = DriverManager.getConnection("jdbc:sqlite:" + dbPath);
        initDb();
    }
    
    private void initDb() throws SQLException {
        Statement stmt = conn.createStatement();
        stmt.execute("""
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY,
                username TEXT UNIQUE,
                email TEXT UNIQUE
            )
        """);
    }
    
    public int createUser(String username, String email) throws SQLException {
        PreparedStatement ps = conn.prepareStatement(
            "INSERT INTO users (username, email) VALUES (?, ?)",
            Statement.RETURN_GENERATED_KEYS
        );
        ps.setString(1, username);
        ps.setString(2, email);
        ps.executeUpdate();
        
        ResultSet rs = ps.getGeneratedKeys();
        return rs.next() ? rs.getInt(1) : -1;
    }
    
    public static void main(String[] args) throws SQLException {
        DatabaseManager db = new DatabaseManager("app.db");
        int userId = db.createUser("john", "john@example.com");
        System.out.println("Created user: " + userId);
    }
}''',
    },
    'C++': {
      'function': '''// TockyCode Generated
#include <iostream>
#include <string>

{{returnType}} {{name}}({{params}}) {
    // Add your implementation here
    return result;
}

int main() {
    auto result = {{name}}({{args}});
    std::cout << "Result: " << result << std::endl;
    return 0;
}''',
      'class': '''// TockyCode Generated
#include <iostream>
#include <vector>
#include <string>

class {{name}} {
private:
    std::vector<std::string> data;
public:
    {{name}}({{init_params}}) {
        // Constructor
    }
    
    void add(const std::string& item) {
        data.push_back(item);
    }
    
    std::vector<std::string> process() {
        return data;
    }
};

int main() {
    {{name}} obj({{init_args}});
    obj.add("test");
    obj.add("demo");
    
    for (const auto& item : obj.process()) {
        std::cout << item << std::endl;
    }
    return 0;
}''',
      'api': '''// TockyCode Generated - C++ REST SDK
#include <cpprest/http_listener.h>
#include <cpprest/json.h>
#include <iostream>

using namespace web;
using namespace http;

class ApiServer {
    http_listener listener;
public:
    ApiServer(utf8string url) : listener(url) {
        listener.support(methods::GET, [](http_request req) {
            req.reply(status_codes::OK, json::value::object({{
                {u"status", json::value::string(u"ok")},
                {u"version", json::value::string(u"1.0.0")}
            }}));
        });
    }
    
    void start() { listener.open().wait(); }
};

int main() {
    ApiServer server("http://localhost:8080");
    server.start();
    std::cout << "Server running on port 8080" << std::endl;
    return 0;
}''',
      'cli': '''// TockyCode Generated - C++ CLI with argparse
#include <iostream>
#include <string>
#include <vector>

struct Options {
    std::string prompt;
    std::string language = "cpp";
    std::string output;
};

Options parseArgs(std::vector<std::string> args) {
    Options opts;
    for (size_t i = 0; i < args.size(); i++) {
        if (args[i] == "-p" || args[i] == "--prompt")
            opts.prompt = args[++i];
        else if (args[i] == "-l" || args[i] == "--language")
            opts.language = args[++i];
        else if (args[i] == "-o" || args[i] == "--output")
            opts.output = args[++i];
    }
    return opts;
}

int main(int argc, char* argv[]) {
    auto opts = parseArgs({argv + 1, argv + argc});
    if (!opts.prompt.empty()) {
        std::cout << "Generating " << opts.language 
                  << " code for: " << opts.prompt << std::endl;
    }
    return 0;
}''',
      'database': '''// TockyCode Generated - SQLite C++
#include <sqlite3.h>
#include <iostream>
#include <string>

class DatabaseManager {
private:
    sqlite3* db;
public:
    DatabaseManager(const std::string& path) {
        sqlite3_open(path.c_str(), &db);
        initDb();
    }
    
    void initDb() {
        const char* sql = R"(
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY,
                username TEXT UNIQUE,
                email TEXT UNIQUE
            )
        )";
        sqlite3_exec(db, sql, nullptr, nullptr, nullptr);
    }
    
    int createUser(const std::string& username, const std::string& email) {
        const char* sql = "INSERT INTO users (username, email) VALUES (?, ?)";
        sqlite3_stmt* stmt;
        sqlite3_prepare_v2(db, sql, -1, &stmt, nullptr);
        sqlite3_bind_text(stmt, 1, username.c_str(), -1, SQLITE_TRANSIENT);
        sqlite3_bind_text(stmt, 2, email.c_str(), -1, SQLITE_TRANSIENT);
        sqlite3_step(stmt);
        return sqlite3_last_insert_rowid(db);
    }
    
    ~DatabaseManager() { sqlite3_close(db); }
};

int main() {
    DatabaseManager db("app.db");
    int userId = db.createUser("john", "john@example.com");
    std::cout << "Created user: " << userId << std::endl;
    return 0;
}''',
    },
    'Go': {
      'function': '''// TockyCode Generated
package main

import "fmt"

func {{name}}({{params}}) {{returnType}} {
    // Add your implementation here
    return result
}

func main() {
    result := {{name}}({{args}})
    fmt.Println("Result:", result)
}''',
      'class': '''// TockyCode Generated
package main

import "fmt"

type {{name}} struct {
    data []interface{}
}

func New{{name}}({{init_params}}) *{{name}} {
    return &{{name}}{
        data: make([]interface{}, 0),
    }
}

func (a *{{name}}) Add(item interface{}) *{{name}} {
    a.data = append(a.data, item)
    return a
}

func (a *{{name}}) Process() []interface{} {
    return a.data
}

func main() {
    obj := New{{name}}({{init_args}})
    obj.Add("test").Add("demo")
    fmt.Println(obj.Process())
}''',
      'api': '''// TockyCode Generated - Gin
package main

import (
    "github.com/gin-gonic/gin"
    "net/http"
)

type Item struct {
    ID   int         `json:"id"`
    Data interface{} `json:"data"`
}

var dataStore []Item

func main() {
    r := gin.Default()
    
    r.GET("/api/health", func(c *gin.Context) {
        c.JSON(http.StatusOK, gin.H{
            "status":  "ok",
            "version": "1.0.0",
        })
    })
    
    r.GET("/api/data", func(c *gin.Context) {
        c.JSON(http.StatusOK, gin.H{"data": dataStore})
    })
    
    r.POST("/api/data", func(c *gin.Context) {
        var item Item
        if err := c.ShouldBindJSON(&item); err != nil {
            c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
            return
        }
        item.ID = len(dataStore) + 1
        dataStore = append(dataStore, item)
        c.JSON(http.StatusCreated, gin.H{"success": true, "data": item})
    })
    
    r.Run(":8080")
}''',
      'cli': '''// TockyCode Generated - Cobra
package main

import (
    "fmt"
    "github.com/spf13/cobra"
)

var rootCmd = &cobra.Command{
    Use:   "tockycode",
    Short: "TockyCode CLI",
    Long:  "Professional AI Code Generator CLI",
}

var generateCmd = &cobra.Command{
    Use:   "generate",
    Short: "Generate code",
    Run: func(cmd *cobra.Command, args []string) {
        prompt, _ := cmd.Flags().GetString("prompt")
        language, _ := cmd.Flags().GetString("language")
        fmt.Printf("Generating %s code for: %s\\n", language, prompt)
    },
}

func init() {
    rootCmd.AddCommand(generateCmd)
    generateCmd.Flags().StringP("prompt", "p", "", "Code prompt")
    generateCmd.Flags().StringP("language", "l", "go", "Language")
}

func main() {
    rootCmd.Execute()
}''',
      'database': '''// TockyCode Generated - Go with SQLite
package main

import (
    "database/sql"
    "fmt"
    _ "github.com/mattn/go-sqlite3"
)

type User struct {
    ID       int
    Username string
    Email    string
}

func main() {
    db, _ := sql.Open("sqlite3", "app.db")
    defer db.Close()
    
    db.Exec(`
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY,
            username TEXT UNIQUE,
            email TEXT UNIQUE
        )
    `)
    
    result, _ := db.Exec("INSERT INTO users (username, email) VALUES (?, ?)", "john", "john@example.com")
    userId, _ := result.LastInsertId()
    fmt.Printf("Created user: %d\\n", userId)
}''',
    },
    'Rust': {
      'function': '''// TockyCode Generated
fn {{name}}({{params}}) -> {{returnType}} {
    // Add your implementation here
    result
}

fn main() {
    let result = {{name}}({{args}});
    println!("Result: {:?}", result);
}''',
      'class': '''// TockyCode Generated
#[derive(Debug, Clone)]
pub struct {{name}} {
    data: Vec<String>,
}

impl {{name}} {
    pub fn new({{init_params}}) -> Self {
        Self {
            data: Vec::new(),
        }
    }
    
    pub fn add(&mut self, item: &str) -> &mut Self {
        self.data.push(item.to_string());
        self
    }
    
    pub fn process(&self) -> Vec<String> {
        self.data.clone()
    }
}

fn main() {
    let mut obj = {{name}}::new({{init_args}});
    obj.add("test").add("demo");
    println!("{:?}", obj.process());
}''',
      'api': '''// TockyCode Generated - Axum
use axum::{routing::get, Router};
use serde::{Deserialize, Serialize};
use std::net::SocketAddr;

#[derive(Serialize, Deserialize)]
struct Item {
    id: i32,
    data: String,
}

async fn health() -> impl axum::response::Json<serde_json::Value> {
    axum::response::json(serde_json::json!({
        "status": "ok",
        "version": "1.0.0"
    }))
}

#[tokio::main]
async fn main() {
    let app = Router::new().route("/api/health", get(health));
    
    let addr = SocketAddr::from(([0, 0, 0, 0], 8080));
    println!("Server running on {}", addr);
    axum::Server::bind(&addr)
        .serve(app.into_make_service())
        .await
        .unwrap();
}''',
      'cli': '''// TockyCode Generated - Clap
use clap::{Parser, Subcommand};

#[derive(Parser)]
#[command(name = "tockycode")]
#[command(about = "TockyCode CLI", long_about = None)]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Subcommand)]
enum Commands {
    Generate {
        #[arg(short, long)]
        prompt: String,
        #[arg(short, long, default_value = "rust")]
        language: String,
    },
}

fn main() {
    let cli = Cli::parse();
    
    match cli.command {
        Commands::Generate { prompt, language } => {
            println!("Generating {} code for: {}", language, prompt);
        }
    }
}''',
      'database': '''// TockyCode Generated - Rust with SQLite
use rusqlite::{Connection, Result};

struct DatabaseManager {
    conn: Connection,
}

impl DatabaseManager {
    fn new(path: &str) -> Result<Self> {
        let conn = Connection::open(path)?;
        Ok(Self { conn })
    }
    
    fn init_db(&self) -> Result<()> {
        self.conn.execute(
            "CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY,
                username TEXT UNIQUE,
                email TEXT UNIQUE
            )",
            [],
        )?;
        Ok(())
    }
    
    fn create_user(&self, username: &str, email: &str) -> Result<i64> {
        self.conn.execute(
            "INSERT INTO users (username, email) VALUES (?, ?)",
            [username, email],
        )?;
        Ok(self.conn.last_insert_rowid())
    }
}

fn main() -> Result<()> {
    let db = DatabaseManager::new("app.db")?;
    db.init_db()?;
    let user_id = db.create_user("john", "john@example.com")?;
    println!("Created user: {}", user_id);
    Ok(())
}''',
    },
    'TypeScript': {
      'function': '''// TockyCode Generated
function {{name}}({{params}}): {{returnType}} {
    // Add your implementation here
    return result;
}

// Usage
const result = {{name}}({{args}});
console.log("Result:", result);''',
      'class': '''// TockyCode Generated
interface Config {
    debug: boolean;
}

class {{name}} {
    private data: string[] = [];
    private config: Config;
    
    constructor(config: Partial<Config> = {}) {
        this.config = { debug: true, ...config };
    }
    
    add(item: string): this {
        this.data.push(item);
        return this;
    }
    
    process(): string[] {
        return [...this.data];
    }
}

// Usage
const obj = new {{name}}({ debug: true });
obj.add("test").add("demo");
console.log(obj.process());

export { {{name}}, Config };''',
      'api': '''// TockyCode Generated - Express.js with TypeScript
import express, { Request, Response, NextFunction } from 'express';
const app = express();
app.use(express.json());

interface Item {
    id: number;
    data: unknown;
}

const dataStore: Item[] = [];

app.get('/api/health', (req: Request, res: Response) => {
    res.json({ status: 'ok', version: '1.0.0' });
});

app.get('/api/data', (req: Request, res: Response) => {
    res.json({ data: dataStore });
});

app.post('/api/data', (req: Request, res: Response) => {
    const item: Item = { id: dataStore.length + 1, ...req.body };
    dataStore.push(item);
    res.json({ success: true, data: item });
});

app.listen(3000, () => console.log('Server on port 3000'));

export default app;''',
      'cli': '''// TockyCode Generated - Commander.js with TypeScript
import { Command } from 'commander';

const program = new Command();

program
    .name('tockycode')
    .description('TockyCode CLI')
    .version('1.0.0');

program
    .command('generate')
    .option('-p, --prompt <prompt>', 'Code prompt')
    .option('-l, --language <language>', 'Language', 'typescript')
    .option('-o, --output <output>', 'Output file')
    .action((options) => {
        console.log("Generating <language> code for: <prompt>");
    });

program.parse();''',
      'database': '''// TockyCode Generated - TypeScript with better-sqlite3
import Database from 'better-sqlite3';

interface User {
    id: number;
    username: string;
    email: string;
}

class DatabaseManager {
    private db: Database.Database;
    
    constructor(dbPath: string) {
        this.db = new Database(dbPath);
        this.initDb();
    }
    
    private initDb(): void {
        this.db.exec(`
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY,
                username TEXT UNIQUE,
                email TEXT UNIQUE
            )
        `);
    }
    
    createUser(username: string, email: string): number {
        const stmt = this.db.prepare(
            'INSERT INTO users (username, email) VALUES (?, ?)'
        );
        const result = stmt.run(username, email);
        return result.lastInsertRowid as number;
    }
}

const db = new DatabaseManager('app.db');
const userId = db.createUser('john', 'john@example.com');
console.log('Created user:', userId);

export { DatabaseManager, User };''',
    },
  };

  String _getCodeFromPrompt(String prompt) {
    final lowerPrompt = prompt.toLowerCase();
    
    // Determine template type
    String templateType = 'function';
    if (lowerPrompt.contains('api') || lowerPrompt.contains('rest') || lowerPrompt.contains('server')) {
      templateType = 'api';
    } else if (lowerPrompt.contains('class')) {
      templateType = 'class';
    } else if (lowerPrompt.contains('cli') || lowerPrompt.contains('command') || lowerPrompt.contains('terminal')) {
      templateType = 'cli';
    } else if (lowerPrompt.contains('database') || lowerPrompt.contains('sql') || lowerPrompt.contains('db')) {
      templateType = 'database';
    }
    
    // Get template for selected language
    final langTemplates = _templates[_selectedLanguage];
    if (langTemplates == null) {
      return '// Language template not available';
    }
    
    final template = langTemplates[templateType] ?? langTemplates['function']!;
    
    // Replace placeholders
    String code = template
        .replaceAll('{{name}}', 'generated_function')
        .replaceAll('{{class_name}}', 'GeneratedClass')
        .replaceAll('{{params}}', '')
        .replaceAll('{{args}}', '')
        .replaceAll('{{init_params}}', '')
        .replaceAll('{{init_args}}', '')
        .replaceAll('{{returnType}}', 'ResultType');
    
    return code;
  }

  void _generateCode() {
    if (_promptController.text.trim().isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please enter a prompt'),
          backgroundColor: Colors.red,
        ),
      );
      return;
    }

    setState(() {
      _isLoading = true;
      _showCode = false;
    });

    // Simulate processing delay for realistic feel
    Future.delayed(const Duration(milliseconds: 800), () {
      setState(() {
        _generatedCode = _getCodeFromPrompt(_promptController.text);
        _isLoading = false;
        _showCode = true;
      });
    });
  }

  void _copyCode() {
    if (_generatedCode.isEmpty) return;
    
    Clipboard.setData(ClipboardData(text: _generatedCode));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Code copied to clipboard!'),
        backgroundColor: Color(0xFF00FF88),
      ),
    );
  }

  void _clearAll() {
    setState(() {
      _promptController.clear();
      _generatedCode = '';
      _showCode = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Row(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              padding: const EdgeInsets.all(8),
              decoration: BoxDecoration(
                color: const Color(0xFF00D9FF).withOpacity(0.2),
                borderRadius: BorderRadius.circular(8),
              ),
              child: const Icon(Icons.code, color: Color(0xFF00D9FF)),
            ),
            const SizedBox(width: 8),
            const Text(
              'TockyCode',
              style: TextStyle(
                fontWeight: FontWeight.bold,
                color: Color(0xFF00D9FF),
              ),
            ),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.info_outline),
            onPressed: () {
              showDialog(
                context: context,
                builder: (context) => AlertDialog(
                  title: const Text('TockyCode'),
                  content: const Column(
                    mainAxisSize: MainAxisSize.min,
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Version: 1.0.0'),
                      Text(''),
                      Text('Professional AI Code Generator'),
                      Text('100% Free • Works Locally'),
                      Text('No Internet Required'),
                    ],
                  ),
                  actions: [
                    TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: const Text('OK'),
                    ),
                  ],
                ),
              );
            },
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Tagline
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  colors: [
                    const Color(0xFF00D9FF).withOpacity(0.1),
                    const Color(0xFF00FF88).withOpacity(0.1),
                  ],
                ),
                borderRadius: BorderRadius.circular(12),
              ),
              child: const Column(
                children: [
                  Text(
                    'Professional AI Code Generator',
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: Colors.white,
                    ),
                    textAlign: TextAlign.center,
                  ),
                  SizedBox(height: 8),
                  Text(
                    '100% Free • Works Locally • No Internet Required',
                    style: TextStyle(
                      fontSize: 12,
                      color: Colors.grey,
                    ),
                    textAlign: TextAlign.center,
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),

            // Language selector
            const Text(
              'Programming Language',
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: Colors.white70,
              ),
            ),
            const SizedBox(height: 8),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16),
              decoration: BoxDecoration(
                color: const Color(0xFF2D2D2D),
                borderRadius: BorderRadius.circular(12),
              ),
              child: DropdownButtonHideUnderline(
                child: DropdownButton<String>(
                  value: _selectedLanguage,
                  isExpanded: true,
                  dropdownColor: const Color(0xFF2D2D2D),
                  items: _languages.map((lang) {
                    return DropdownMenuItem(
                      value: lang,
                      child: Text(lang),
                    );
                  }).toList(),
                  onChanged: (value) {
                    setState(() {
                      _selectedLanguage = value!;
                    });
                  },
                ),
              ),
            ),
            const SizedBox(height: 20),

            // Prompt input
            const Text(
              'Describe what you want to code',
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w500,
                color: Colors.white70,
              ),
            ),
            const SizedBox(height: 8),
            TextField(
              controller: _promptController,
              maxLines: 4,
              decoration: const InputDecoration(
                hintText: 'e.g., create a REST API with Flask, create a class for data processing,\ncreate a function to calculate fibonacci, build a CLI tool',
                hintStyle: TextStyle(color: Colors.grey),
              ),
              style: const TextStyle(color: Colors.white),
            ),
            const SizedBox(height: 20),

            // Generate button
            ElevatedButton.icon(
              onPressed: _isLoading ? null : _generateCode,
              icon: _isLoading
                  ? const SizedBox(
                      width: 20,
                      height: 20,
                      child: CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.black,
                      ),
                    )
                  : const Icon(Icons.auto_awesome),
              label: Text(
                _isLoading ? 'Generating...' : 'Generate Code',
                style: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
              ),
            ),
            const SizedBox(height: 20),

            // Generated code section
            if (_showCode) ...[
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  const Text(
                    'Generated Code',
                    style: TextStyle(
                      fontSize: 14,
                      fontWeight: FontWeight.w500,
                      color: Colors.white70,
                    ),
                  ),
                  Row(
                    children: [
                      IconButton(
                        icon: const Icon(Icons.copy, size: 20),
                        color: const Color(0xFF00D9FF),
                        onPressed: _copyCode,
                        tooltip: 'Copy to clipboard',
                      ),
                      IconButton(
                        icon: const Icon(Icons.clear, size: 20),
                        color: Colors.grey,
                        onPressed: _clearAll,
                        tooltip: 'Clear',
                      ),
                    ],
                  ),
                ],
              ),
              const SizedBox(height: 8),
              Container(
                width: double.infinity,
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: const Color(0xFF1A1A1A),
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(
                    color: const Color(0xFF00FF88).withOpacity(0.3),
                  ),
                ),
                child: SelectableText(
                  _generatedCode,
                  style: const TextStyle(
                    fontFamily: 'monospace',
                    fontSize: 13,
                    color: Color(0xFF00FF88),
                    height: 1.5,
                  ),
                ),
              ),
            ],

            // Quick prompts
            if (!_showCode && !_isLoading) ...[
              const SizedBox(height: 24),
              const Text(
                'Quick Examples',
                style: TextStyle(
                  fontSize: 14,
                  fontWeight: FontWeight.w500,
                  color: Colors.white70,
                ),
              ),
              const SizedBox(height: 12),
              Wrap(
                spacing: 8,
                runSpacing: 8,
                children: [
                  _buildQuickPrompt('REST API with Flask'),
                  _buildQuickPrompt('Data Processing Class'),
                  _buildQuickPrompt('CLI Tool'),
                  _buildQuickPrompt('SQL Database'),
                  _buildQuickPrompt('Async Function'),
                ],
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildQuickPrompt(String text) {
    return ActionChip(
      label: Text(text, style: const TextStyle(fontSize: 12)),
      backgroundColor: const Color(0xFF2D2D2D),
      labelStyle: const TextStyle(color: Colors.white70),
      onPressed: () {
        _promptController.text = text;
      },
    );
  }

  @override
  void dispose() {
    _promptController.dispose();
    super.dispose();
  }
}